---
- name: Set apt-cache if available
  template: src=sources.list.j2 dest=/etc/apt/sources.list
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
- name: install package
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - sudo
    - rsync
    - vim
    - git
    - htop
    - python-pycurl
    - apt-transport-https
