---
- name: Set apt-cache if available
  template: src=sources.list.j2 dest=/etc/apt/sources.list
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
- name: install htop
  apt: pkg=htop state=latest
- name: install git
  apt: pkg=git state=latest
- name: install vim
  apt: pkg=vim state=latest
- name: install rsync
  apt: pkg=rsync state=latest
- name: install curl
  apt: pkg=curl state=latest
- name: install python-pycurl
  apt: pkg=python-pycurl state=latest
- name: install sudo
  apt: pkg=sudo state=latest
