---
- name: install htop
  apt: pkg=htop state=latest
- name: install git
  apt: pkg=git state=latest
- name: install vim
  apt: pkg=vim state=latest
- name: install rsync
  apt: pkg=rsync state=latest
- name: install curl
  apt: pkg=curl state=latest
- name: install python-pycurl
  apt: pkg=python-pycurl state=latest
