- name: Add New Relic repoistory
  apt_repository: repo='deb http://apt.newrelic.com/debian/ newrelic non-free' state=present

- name: Add New Relic key
  apt_key: url=http://download.newrelic.com/548C16BF.gpg state=present

- name: Install New Relic
  apt: update_cache=yes pkg=newrelic-sysmond state=present

- name: Set New Relic License
  shell: nrsysmond-config --set license_key={{ new_relic_key }}

- name: Start New Relic Service
  service: name=newrelic-sysmond state=started
