# Add apt keys
  - name: add key for ppa python repository
    apt_key: keyserver=keyserver.ubuntu.com id=DB82666C state=present

# Add extra repositories
  - name: Add ppa python repository
    apt_repository: repo='deb http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu {{ ansible_distribution_release }} main' state=present update_cache=yes

# Update python version
  - name: ensure python2.7 tatest  is installed
    apt:
      pkg: python2.7
      state: latest
