- user:
    name: "{{ item.username }}"
    comment: "Dreamhack Team network user"
    group: sudo
    shell: /bin/bash
  loop: "{{ base_users }}"

- name: Set up authorized_keys for the Admin user
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
  loop: "{{ base_users }}"

- name: configure 30-{{ item.username }} sudoers
  lineinfile:
    dest: /etc/sudoers.d/30-{{ item.username }}
    owner: root
    group: root
    mode: 0440
    line: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes
    validate: 'visudo -cf %s'
  loop: "{{ base_users }}"
